### ISSUE TITLE
Workstation installation is overwriting chef-client symlink with non-existent destination

### ISSUE THREAD

**Issue by gdavison** [mattray/managed_chef_server-cookbook#40]
Even if only Chef Workstation is installed on a machine, the `_workstation` recipe is overwriting the `chef-client` symlink with `/opt/chef/bin/chef-client`, which does't exist.

Steps to reproduce:
1. Create a machine with Chef Workstation, such as https://github.com/irvingpop/packer-chef-highperf-centos-ami
1. Verify the target of the symlink `/bin/chef-client` points to `/opt/chef-workstation/bin/chef-client`
2. Run `chef-client` with `run_list 'managed_chef_server::default', 'managed_chef_server::managed_organization'`.
3. The symlink `/bin/chef-client` now points to `/opt/chef/bin/chef-client`, but `/opt/chef` does not exist.

Expected behaviour:

The symlink `/bin/chef-client` should still point to `/opt/chef-workstation/bin/chef-client`.

**Comment by mattray** [comment]
I'll try to address this in the next week with an updated release.
